// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejjzxkfjxwyofxjrzkks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqanp4a2ZqeHd5b2Z4anJ6a2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzYyOTYsImV4cCI6MjA3Nzc1MjI5Nn0.vYNRGxGkDZo4MessbZ9jEG4FpzfgRlbmh5_ZPR2JNtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});